name: Autograding Tests
on: ["push", "repository_dispatch"]
permissions:
  checks: write
  actions: read
  contents: read
  statuses: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: File Existence Check
        id: file-existence-check
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: File Existence Check
          command: "test -f HelloWorld.java"
          timeout: 10
          max-score: 10
      - name: Execution Check
        id: execution-check
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Run Check - HelloWorld.java
          setup-command: "chmod +x ./run_tests.sh"
          command: "./run_tests.sh"
          timeout: 10
          max-score: 90
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          FILE-EXISTENCE-CHECK_RESULTS: "${{steps.file-existence-check.outputs.result}}"
          EXECUTION-CHECK_RESULTS: "${{steps.execution-check.outputs.result}}"
        with:
          runners: file-existence-check,execution-check